# Generated by Django 4.2.3 on 2023-10-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_commentmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel",
            old_name="commnet",
            new_name="comment",
        ),
    ]
