# Generated by Django 4.2.3 on 2023-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_rename_commnet_commentmodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
    ]
