# Generated by Django 4.2.3 on 2023-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, unique=True, verbose_name="date joined"
            ),
        ),
    ]
