# Generated by Django 4.2.3 on 2023-10-07 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usermodel_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="user_uniqe_id",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
