# Generated by Django 4.2.3 on 2023-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_usermodel_user_uniqe_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="address",
            new_name="bio",
        ),
    ]
